# Use root/example as user/password credentials

services:

  app:
    image: gamermaker/bria-nutrition:latest
    restart: always
    ports:
       - 5173:3000
    env_file:
      - .env

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
